name: Pipeline de CI/CD
run-name: Deploy in live by ${{ github.actor }} 
on: 
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje de bienvenida
        run: |
             echo "¡Bienvenido a nuestro proyecto ${{ vars.NAME }}!"
             echo "Estamos construyendo y probando nuestro código."
             echo "¡Gracias por contribuir!"

      - name: Echo Secreto
        run: echo "${{ secrets.SECRETO }}" > secreto.txt
